### PR TITLE
fix: add ReturnLpTokens callback to multi asset case

### PR DESCRIPTION
**Pull request by apollo-pacman**
Closes https://github.com/apollodao/apollo-vaults/issues/134

### CODE REVIEW

**Review by apollo-sturdy — CHANGES_REQUESTED** [review]
Since you moved the `ReturnLpTokens` callback out to be the last message of `execute_balancing_provide_liquidity`, we should also remove the `ReturnLpTokens` callback in `execute_callback_single_sided_join`.

**Comment by apollo-pacman** [comment]
> Since you moved the `ReturnLpTokens` callback out to be the last message of `execute_balancing_provide_liquidity`, we should also remove the `ReturnLpTokens` callback in `execute_callback_single_sided_join`.

@apollo-sturdy when we remove the `ReturnLpTokens` from `execute_callback_single_sided_join` the query for LP token balance is no longer used and I don't see a reason to keep the single sided join msg as a callback. Thoughts?

**Comment by apollo-sturdy** [comment]
> > Since you moved the `ReturnLpTokens` callback out to be the last message of `execute_balancing_provide_liquidity`, we should also remove the `ReturnLpTokens` callback in `execute_callback_single_sided_join`.
> 
> @apollo-sturdy when we remove the `ReturnLpTokens` from `execute_callback_single_sided_join` the query for LP token balance is no longer used and I don't see a reason to keep the single sided join msg as a callback. Thoughts?

This won't work since the reason we are doing a callback for each single sided provision is that in cw-dex `provide_liquidity` we first do a simulation. This simulation won't be correct if we issue multiple calls in the same message. Pls revert and perhaps add a comment above the implementation of single sided callback with this explanation.

**Comment by apollo-pacman** [comment]
> > > Since you moved the `ReturnLpTokens` callback out to be the last message of `execute_balancing_provide_liquidity`, we should also remove the `ReturnLpTokens` callback in `execute_callback_single_sided_join`.
> > 
> > 
> > @apollo-sturdy when we remove the `ReturnLpTokens` from `execute_callback_single_sided_join` the query for LP token balance is no longer used and I don't see a reason to keep the single sided join msg as a callback. Thoughts?
> 
> This won't work since the reason we are doing a callback for each single sided provision is that in cw-dex `provide_liquidity` we first do a simulation. This simulation won't be correct if we issue multiple calls in the same message. Pls revert and perhaps add a comment above the implementation of single sided callback with this explanation.

Ahhh yeah. Completely forgot about that...Will fix

**Review by apollo-sturdy — APPROVED** [review]
lgtm

**Pull request merged**
